
CREATE DATABASE RentalCar

CREATE TABLE Brands
(
	Id INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE Colors
(
	Id INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(50) UNIQUE NOT NULL,
	Code NVARCHAR(20) NOT NULL
)

CREATE TABLE Cars
(
	Id INT IDENTITY PRIMARY KEY,
	ModelYear datetime NOT NULL,
	DailyPrice money CHECK(DailyPrice>0) NOT NULL,
	[Description] NVARCHAR(500),
	BrandId INT FOREIGN KEY REFERENCES Brands(Id)
)

CREATE TABLE CarColors
(
	Id INT IDENTITY PRIMARY KEY,
	CarId INT FOREIGN KEY REFERENCES Cars(Id),
	ColorId INT FOREIGN KEY REFERENCES Colors(Id)
)